### ISSUE TITLE
End User - latest update

### ISSUE THREAD

**Issue by froggiD** [CodingFriends/Tincta#29]
1) When I clicked GO TO WEBSITE from the HELP TAB, it comes back not found. https://wokabulary.com/software/tincta

2) Could we please have the option to display the icon names as well as the icons? Much easier for us old folks.

3) Why can I no longer right-click and close a file that way? I used that feature extensively.

Thank you!

**Comment by greimers** [comment]
1. Oops. Will be fixed of course.
2. That's a design dilemma. We prefer the icons only as most other apps have it today (Firefox, Safari, Finder...). We would like to have it customizable but that would also allow you to change the icon size, which does not work well at the moment. Maybe we can add a checkbox in the preferences. We'll look into it.
3. Right click where? In any case this is not an intended feature because I have never heard of this 😄. We do not use right-click actions in general. Maybe it is something that was automatically provided by the system and has changed with a macOS update?

PS: I'll split this in multiple issues and close this one.

**Comment by greimers** [comment]
@froggiD 
Please provide more info on the right click issue in #33
