### ISSUE TITLE
Save Dialog

### ISSUE THREAD

**Issue by jdoej** [CodingFriends/Tincta#36]
Change the behavior of the save dialog window so people can delete using Command+D instead of having to navigate with a mouse. Enclosed is a screengrab showing how TextWrangler would allow you to use Command+D to delete the file you were working on.
[textwrangler-10.14-cmd_d.mp4.zip](https://github.com/CodingFriends/Tincta/files/4245037/textwrangler-10.14-cmd_d.mp4.zip)

**Comment by greimers** [comment]
Thanks for the details.
I am very sure that TextWrangler is a Carbon app and either uses some old Carbon API for the save dialog or they actually create the save dialog themselves. 

For Tincta as a native Cocoa app, we use the system provided save dialog which does not allow such customization. I think it is not an option to write a custom save dialog because file browsing is not possible for a sandboxed app without the system dialog.
We could show an additional dialog before the actual save dialog, but that would require two clicks and degrade user experience.

In fact, I am wondering if any app distributed in the App Store offers the TextWranger like behavior.
If anybody has any more hints on this, please let us know.

**Comment by jdoej** [comment]
Hi - I just discovered you can use a feature in Systems Preferences >> Keyboard >> Shortcuts: Use keyboard navigation to move focus between controls. Thank you.
[tincta-keyboard_nav.mp4.zip](https://github.com/CodingFriends/Tincta/files/4290761/tincta-keyboard_nav.mp4.zip)
